Principal Component Analysis (PCA)

In [2]:
import numpy as np
import pandas as pd

In [124]:
M=np.matrix([[1,2,3,4],[5,5,6,7],[1,4,2,3],[5,3,2,1],[8,1,2,2]])
data=pd.DataFrame(M,columns=['F1','F2','F3','F4'])
data

F1  F2  F3  F4
0   1   2   3   4
1   5   5   6   7
2   1   4   2   3
3   5   3   2   1
4   8   1   2   2

In [6]:
data_std=(data-data.mean())/data.std()
data_std

F1        F2        F3        F4
0 -1.000000 -0.632456  0.000000  0.260623
1  0.333333  1.264911  1.732051  1.563740
2 -1.000000  0.632456 -0.577350 -0.173749
3  0.333333  0.000000 -0.577350 -1.042493
4  1.333333 -1.264911 -0.577350 -0.608121

4

In [44]:
dt=pd.DataFrame()
columns=data_std.columns
for i in range(data_std.shape[1]):
    ls=[]
    for f in range(data_std.shape[1]):
        val=(data_std.iloc[:,i].values@data_std.iloc[:,f].values)/len(data_std)
        ls.append(val)
    dt[columns[i]]=ls
dt.index=columns

In [45]:
dt

F1        F2        F3        F4
F1  0.800000 -0.252982  0.038490 -0.144791
F2 -0.252982  0.800000  0.511208  0.494498
F3  0.038490  0.511208  0.800000  0.752355
F4 -0.144791  0.494498  0.752355  0.800000

In [47]:
M=np.matrix(dt)

In [75]:
eign_values,eign_vectors=np.linalg.eig(M)

In [76]:
print(eign_values)
print(eign_vectors)


[2.01263459 0.8522308  0.31510964 0.02002497]
[[ 0.16195986 -0.91705888 -0.30707099  0.19616173]
 [-0.52404813  0.20692161 -0.81731886  0.12061043]
 [-0.58589647 -0.3205394   0.1882497  -0.72009851]
 [-0.59654663 -0.11593512  0.44973251  0.65454704]]


In [78]:
eign_values_indices=[]
eign_values=list(eign_values)
eign_values_sorted=sorted(eign_values,reverse=True)[:2]
eign_values_indices.append(eign_values.index(eign_values_sorted[0]))
eign_values_indices.append(eign_values.index(eign_values_sorted[1]))
print(eign_values_indices)

[0, 1]


In [103]:
v1=eign_vectors[:,eign_values_indices[0]]
v2=eign_vectors[:,eign_values_indices[1]]
v=np.hstack((v1,v2))
v

matrix([[ 0.16195986, -0.91705888],
        [-0.52404813,  0.20692161],
        [-0.58589647, -0.3205394 ],
        [-0.59654663, -0.11593512]])

In [109]:
dataset=pd.DataFrame(columns=['nf1','nf2'])
dataset[['nf1','nf2']]=data_std@v

In [110]:
dataset

nf1       nf2
0  0.014003  0.755975
1 -2.556534 -0.780432
2 -0.051480  1.253135
3  1.014150  0.000239
4  1.579861 -1.228917